# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], max_length=10),
        ),
    ]
