# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20161005_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
